[package]
name = "FerumSTD"
version = "0.1.0"
upgrade_policy = "compatible"
license = "Apache-2.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }

[addresses]
ferum_std="0xcf78eeed73fdfd11afca8a5e19ac52c8444fce37bcb04c27d52867ec7caceb35"